import 'package:flutter/material.dart';
import 'package:habit_tracker/models/habit.dart';
import 'package:habit_tracker/screens/add_habit_screen.dart';
import 'package:habit_tracker/screens/edit_habit_screen.dart';
import 'package:habit_tracker/services/database_service.dart';

class HomeScreen extends StatefulWidget {
  final DatabaseService? dbService;

  const HomeScreen({super.key, this.dbService});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late final DatabaseService _dbService;

  @override
  void initState() {
    super.initState();
    _dbService = widget.dbService ?? DatabaseService();
  }

  void _addHabit() async {
    // We expect AddHabitScreen to return a Map with 'name' and 'theme'
    final result = await Navigator.of(context).push<Map<String, String>>(
      MaterialPageRoute(builder: (context) => const AddHabitScreen()),
    );

    if (result != null && result['name'] != null && result['theme'] != null) {
      // The ID will be generated by Firestore, so we pass a dummy one here.
      // The DatabaseService's addHabit method will use Firestore's add() which generates an ID.
      final newHabit = Habit(id: 'dummy_id', name: result['name']!, theme: result['theme']!);
      await _dbService.addHabit(newHabit);
    }
  }

  void _toggleHabitCompleted(Habit habit) {
    final isCompleted = !habit.isCompleted;
    int newStreak = habit.streak;
    if (isCompleted) {
      newStreak++;
    } else {
      if (newStreak > 0) {
        newStreak--;
      }
    }
    final updatedHabit = habit.copyWith(
      isCompleted: isCompleted,
      streak: newStreak,
    );
    _dbService.updateHabit(updatedHabit);
  }

  void _deleteHabit(Habit habit) {
    _dbService.deleteHabit(habit.id);
  }

  void _editHabit(Habit habit) async {
    // EditHabitScreen can stay as it is, as it returns a full Habit object
    // which we can then use to update the database.
    final updatedHabit = await Navigator.of(context).push<Habit>(
      MaterialPageRoute(builder: (context) => EditHabitScreen(habit: habit)),
    );

    if (updatedHabit != null) {
      // We need to make sure the updatedHabit from EditHabitScreen has the correct id.
      // Let's assume EditHabitScreen preserves the id.
      _dbService.updateHabit(updatedHabit);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Habit Tracker'),
      ),
      body: StreamBuilder<List<Habit>>(
        stream: _dbService.getHabits(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }
          if (!snapshot.hasData || snapshot.data!.isEmpty) {
            return const Center(child: Text('No habits yet. Add one!'));
          }

          final habits = snapshot.data!;

          return ListView.builder(
            itemCount: habits.length,
            itemBuilder: (context, index) {
              final habit = habits[index];
              return Dismissible(
                key: ValueKey(habit.id), // Use habit.id for a stable key
                onDismissed: (direction) {
                  _deleteHabit(habit);
                },
                background: Container(
                  color: Colors.red,
                  alignment: Alignment.centerRight,
                  padding: const EdgeInsets.only(right: 20.0),
                  child: const Icon(Icons.delete, color: Colors.white),
                ),
                child: ListTile(
                  onTap: () => _editHabit(habit),
                  leading: CircleAvatar(
                    child: Text('${habit.streak}'),
                  ),
                  title: Text(habit.name),
                  subtitle: Text(habit.theme),
                  trailing: Checkbox(
                    value: habit.isCompleted,
                    onChanged: (value) {
                      _toggleHabitCompleted(habit);
                    },
                  ),
                ),
              );
            },
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _addHabit,
        child: const Icon(Icons.add),
      ),
    );
  }
}
